version: ‘2.1’
services:
 zookeeper-1:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper1
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 22181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
 
 zookeeper-2:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper2
   environment:
     ZOOKEEPER_SERVER_ID: 2
     ZOOKEEPER_CLIENT_PORT: 32181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
 zookeeper-3:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper3
   environment:
     ZOOKEEPER_SERVER_ID: 3
     ZOOKEEPER_CLIENT_PORT: 42181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
  
 kafka-1:
   image: confluentinc/cp-kafka:latest
   container_name: kafka1
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_LISTENERS: PLAINTEXT://:9091
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091
   ports:
     - "9091:9091"
 
 kafka-2:
   image: confluentinc/cp-kafka:latest
   container_name: kafka2
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_LISTENERS: PLAINTEXT://:9092
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
   ports:
     - "9092:9092"
 
 kafka-3:
   image: confluentinc/cp-kafka:latest
   container_name: kafka3
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_LISTENERS: PLAINTEXT://:9093
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
   ports:
     - "9093:9093" 