
services:
  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - pubsub
    volumes:
      - ./DB:/data/db
    restart: unless-stopped
  sub3:
    build: ./subscriber3
    networks:
      - pubsub
    container_name: "sub3"
    depends_on:
      - mongodb

  sub2:
    build: ./subscriber2
    networks:
      - pubsub
    container_name: "sub2"
    depends_on:
      - mongodb
  sub1:
    build: ./subscriber1
    networks:
      - pubsub
    container_name: "sub1"
    depends_on:
      - mongodb
  ip1:
    build: ./IP1
    networks:
      - pubsub
    container_name: "IP1"
    depends_on:
      - mongodb
      - subscriber1
      - subscriber2
      - subscriber3
  ip2:
    build: ./IP2
    networks:
      - pubsub
    container_name: "IP2"
    depends_on:
      - mongodb
      - subscriber1
      - subscriber2
      - subscriber3
  ip3:
    build: ./IP3
    networks:
      - pubsub
    container_name: "IP3"
    depends_on:
      - mongodb
      - subscriber1
      - subscriber2
      - subscriber3
  pub1:
    build: ./publisher1
    networks:
      - pubsub
    container_name: "pub1"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub2:
    build: ./publisher1
    networks:
      - pubsub
    container_name: "pub2"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub3:
    build: ./publisher3
    networks:
      - pubsub
    container_name: "pub3"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub4:
    build: ./publisher4
    networks:
      - pubsub
    container_name: "pub4"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub5:
    build: ./publisher5
    networks:
      - pubsub
    container_name: "pub5"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub6:
    build: ./publisher6
    networks:
      - pubsub
    container_name: "pub6"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub7:
    build: ./publisher7
    networks:
      - pubsub
    container_name: "pub7"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
  pub8:
    build: ./publisher8
    networks:
      - pubsub
    container_name: "pub8"
    depends_on:
      - mongodb
      - IP1
      - IP2
      - IP3
networks: 
  pubsub:
    external: false
    name: pubsub  